import { DashboardData, ExecutiveBrief, TopIssue } from '../../../types/dashboard';

export const generateExecutiveBrief = (
    data: DashboardData,
    type: 'DAILY' | 'WEEKLY' | 'COMPLIANCE',
    scopeName: string
): ExecutiveBrief => {
    const now = new Date().toLocaleString();
    const risks = data.topIssues.filter(i => i.category === 'RISK');
    const prodIssues = data.topIssues.filter(i => i.category === 'PRODUCTIVITY');
    const topPerforming = [...data.departments].sort((a, b) => b.focusIndex - a.focusIndex).slice(0, 1);
    const bottomPerforming = [...data.departments].sort((a, b) => a.focusIndex - b.focusIndex).slice(0, 1);

    let summary = '';
    let conclusion = '';
    let disclaimer = 'This report was generated by local AI rules based on telemetry data. No external LLM was used.';

    if (type === 'DAILY') {
        summary = `Productivity across ${scopeName} is ${data.kpis.focusIndex.trend?.isGood ? 'stable' : 'declining'}. User activity averages ${data.kpis.activeMinutes.value}. Detected ${risks.length} main risk vectors today.`;
        conclusion = `Recommended Focus: Address ${risks.length > 0 ? risks[0].title : 'minor productivity gaps in ' + bottomPerforming[0]?.name}.`;
    } else if (type === 'WEEKLY') {
        summary = `Weekly Review for ${scopeName}: Overall health is ${parseInt(data.kpis.dataHealth.value as string) > 90 ? 'Good' : 'Needs Attention'}. Top performing team is ${topPerforming[0]?.name}. Risks have ${data.kpis.riskAlerts.trend?.direction} detected trend.`;
        conclusion = `Strategy: Reward ${topPerforming[0]?.name} and audit ${bottomPerforming[0]?.name} for process bottlenecks.`;
    } else if (type === 'COMPLIANCE') {
        summary = `Compliance Snapshot: Compliance Rate ${data.kpis.policyCompliance.value}. Total Blocking Events: ${data.riskBreakdown.find(r => r.type === 'BLOCKED')?.count || 0}.`;
        conclusion = `Action Required: ${risks.length} P1 Risk Issues require immediate mitigation.`;
    }

    return {
        type,
        target: scopeName,
        generatedAt: now,
        summary,
        topIssues: type === 'COMPLIANCE' ? risks : data.topIssues.slice(0, 5),
        deptRankings: {
            top: topPerforming.map(d => `${d.name} (${d.focusIndex})`),
            bottom: bottomPerforming.map(d => `${d.name} (${d.focusIndex})`)
        },
        conclusion,
        disclaimer
    };
};
