export type ScopeType = 'ORG' | 'DEPT' | 'TEAM';
export type TimeRange = 'TODAY' | '24H' | '7D' | '30D';
export type DataViewMode = 'PRODUCTIVITY' | 'RISK' | 'HEALTH';

export interface DashboardFilterState {
    timeRange: TimeRange;
    scopeId: string; // 'root' or deptId
    scopeType: ScopeType;
    includeOffHours: boolean;
    viewMode: DataViewMode;
}

export interface KpiMetric {
    id: string;
    label: string;
    value: string | number;
    unit?: string;
    trend?: {
        value: number; // percent change
        direction: 'up' | 'down' | 'flat';
        isGood: boolean; // e.g. up is good for Active, bad for Risk
        label?: string; // "vs yesterday"
    };
    color?: string; // 'neutral', 'success', 'warning', 'danger'
    drilldown?: string; // route path
}

export interface ExecutiveKPIs {
    onlineDevices: KpiMetric;
    activeMinutes: KpiMetric; // Per user avg
    idleRatio: KpiMetric;
    focusIndex: KpiMetric; // 0-100
    productiveAppShare: KpiMetric;
    riskAlerts: KpiMetric;
    policyCompliance: KpiMetric;
    dataHealth: KpiMetric;
}

export interface DepartmentStats {
    id: string;
    name: string;
    userCount: number;
    deviceCount: number;

    // Core Metrics
    activeMinPerUser: number;
    idleRatio: number;
    focusIndex: number; // 0-100
    riskScore: number; // 0-100
    onlineRate: number; // 0-100

    // Metadata for drilldown
    topRiskType: string;
    trend: 'improving' | 'stable' | 'degrading';
}

export interface TrendPoint {
    time: string; // ISO or label
    active: number;
    idle: number;
    risk: number;
    health: number;
}

export interface TopIssue {
    id: string;
    title: string;
    category: 'PRODUCTIVITY' | 'RISK' | 'HEALTH';
    severity: 'P1' | 'P2' | 'P3';
    confidence: number; // 0-100
    impact: string; // "3 Depts", "15 Users"
    evidence: string; // Short summary
    recommendation: {
        label: string;
        action: 'NAVIGATE' | 'EXPORT' | 'DIAGNOSE';
        target?: string;
    };
}

export interface ExecutiveBrief {
    type: 'DAILY' | 'WEEKLY' | 'COMPLIANCE';
    target: string; // Scope Name
    generatedAt: string;
    summary: string;
    topIssues: TopIssue[];
    deptRankings: { top: string[], bottom: string[] };
    conclusion: string;
    disclaimer: string;
}

export interface DashboardData {
    generatedAt: string;
    kpis: ExecutiveKPIs;
    departments: DepartmentStats[];
    trends: {
        daily: TrendPoint[];
        hourly: TrendPoint[];
    };
    riskBreakdown: { type: string; count: number }[];
    topIssues: TopIssue[]; // Generated by rule engine
}
